# Import Libraries

In [3]:
import cv2 
import numpy as np
from pathlib import Path
import time


# Accessing Correct Directory for Videos

In [4]:
# getting path to whole project as a string
root = str(Path.cwd().parent)

# creating path object to data folder
data_dir  = Path(root + "/data")

# create list of ladder beam MP4 videos 
videos = list(data_dir.glob("ladder beam videos/*.MP4"))

# Load First Video

### Function to watch video

In [5]:
def watch_video(p: Path): 
    # create VideoCapture object with first video
    cap = cv2.VideoCapture(p)

    cv2.startWindowThread()

    # Check if video opened successfully
    if (cap.isOpened() == False):
        print("Error opening video file.")

    # Read until video is completed
    while cap.isOpened():
        # Capture frame by frame
        ret, frame = cap.read()
        if ret:
            cv2.imshow('Frame', frame)

            key = cv2.waitKey(1)
            # Press Q to quit
            if key == ord('q'):
                break
            # Press P to pause
            if key == ord('p'):
                cv2.waitKey(-1)
        else:
            break
    cap.release()
    cv2.destroyWindow('Frame')

    # solution to weird bug to close video window
    for i in range(4):
        cv2.waitKey(1)

    


### Watch Mouse #1 - Run #1

In [6]:
watch_video(str(videos[0]))

# Convert Video to Images (for training)

### Function to convert video to images

In [21]:
def video_to_frames(input_loc, output_loc):
    """Function to extract frames from input video file
    and save them as separate frames in an output directory.
    Args:
        input_loc: Input video file.
        output_loc: Output directory to save the frames.
    Returns:
        None
    """
    try:
        Path(output_loc).mkdir(parents=True, exist_ok=True)
    except OSError:
        pass
    # Log the time
    time_start = time.time()
    # Start capturing the feed
    cap = cv2.VideoCapture(input_loc)
    # Find the number of frames
    video_length = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) - 1
    print ("Number of frames: ", video_length)
    frame_num = 0
    print ("Converting video..\n")
    # Start converting the video
    while cap.isOpened():
        if (frame_num % 5 == 0): 
        # Extract the frame
            ret, image = cap.read()
            print(image)
            if not ret:
                continue
        # Write the results back to output location.
            cv2.imwrite(output_loc + "/%#05d.jpg" % (frame_num+1), image)
        frame_num = frame_num + 1
        # If there are no more frames left
        if (frame_num > (video_length-1)):
            # Log the time again
            time_end = time.time()
            break
    # Release the feed
    cap.release()
    # Print stats
    print ("Done extracting frames.\n%d frames extracted" % frame_num)
    print ("It took %d seconds forconversion." % (time_end-time_start))

### Convert Mouse #1 - Run #1 to Images

In [22]:
video_to_frames(str(videos[0]), str(data_dir) + "/images")

Number of frames:  2189
Converting video..

[[[45 38 57]
  [45 38 57]
  [45 38 57]
  ...
  [52 55 60]
  [52 53 58]
  [52 53 58]]

 [[45 38 57]
  [46 39 58]
  [46 39 58]
  ...
  [54 57 62]
  [52 53 58]
  [52 53 58]]

 [[38 40 56]
  [38 40 56]
  [39 41 57]
  ...
  [56 56 63]
  [58 55 62]
  [55 52 59]]

 ...

 [[13 25 30]
  [13 25 30]
  [15 24 30]
  ...
  [30 37 50]
  [33 40 53]
  [33 40 53]]

 [[ 8 25 29]
  [ 8 25 29]
  [12 24 29]
  ...
  [41 40 57]
  [42 41 58]
  [42 41 58]]

 [[ 7 24 28]
  [ 7 24 28]
  [11 23 28]
  ...
  [42 41 58]
  [45 44 61]
  [45 44 61]]]
[[[47 31 55]
  [49 33 57]
  [48 35 58]
  ...
  [48 53 59]
  [51 56 62]
  [52 57 63]]

 [[47 31 55]
  [49 33 57]
  [48 35 58]
  ...
  [52 57 63]
  [50 55 61]
  [48 53 59]]

 [[37 37 58]
  [37 37 58]
  [37 37 58]
  ...
  [55 60 66]
  [54 56 63]
  [50 52 59]]

 ...

 [[13 25 30]
  [13 25 30]
  [15 24 30]
  ...
  [28 40 52]
  [32 44 56]
  [35 47 59]]

 [[ 8 25 29]
  [ 8 25 29]
  [12 24 29]
  ...
  [30 41 56]
  [39 50 65]
  [42 53 68]]

# Object (Paw) Detection

In [9]:
m1_r1 = str(videos[0]) # path to video of mouse 1's first time completing ladder beam task